const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const https = require('https');

// --- Config ---
// --- Config ---
const PACKAGE_JSON_PATH = path.join(__dirname, '../package.json');
const VERSION_TS_PATH = path.join(__dirname, '../src/version.ts');
const ENV_PATH = path.join(__dirname, '../.env.local');
// Correct: 3 levels up from apps/web/scripts -> apps/web -> apps -> ROOT
const PROJECT_ROOT = path.resolve(__dirname, '../../../');
const CHANGELOG_PATH = path.join(PROJECT_ROOT, 'CHANGELOG.md');

// Load .env.local manually
if (fs.existsSync(ENV_PATH)) {
    const envConfig = fs.readFileSync(ENV_PATH, 'utf8');
    envConfig.split('\n').forEach(line => {
        const [key, value] = line.split('=');
        if (key && value) {
            process.env[key.trim()] = value.trim();
        }
    });
}

const GROQ_API_KEY = process.env.GROQ_API_KEY;

if (!GROQ_API_KEY) {
    console.error("❌ Error: GROQ_API_KEY is not set in .env.local or environment variables.");
    process.exit(1);
}

// --- Helpers ---
// The 'run' helper function is no longer used as execSync calls are now direct with cwd option.

async function generateChangelog(commits) {
    console.log("🤖 Asking Llama 3 (via Groq) to write changelog...");

    // Fallback if no commits
    if (!commits) return "No significant changes.";

    const prompt = `
You are a cool tech lead for a startup. Summarize these git commits into a concise, readable changelog entry.
Use emojis. Group by Features (✨), Fixes (🐛), and Improvements (⚡️).
Ignore 'wip', 'chore', or 'merge' commits unless important.
Keep it punchy and exciting for users.

Commits:
${commits}

Format output as markdown (just the content, no title or markdown block ticks).
`;

    const data = JSON.stringify({
        model: "llama-3.1-8b-instant",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7,
        max_tokens: 500
    });

    return new Promise((resolve, reject) => {
        const req = https.request({
            hostname: 'api.groq.com',
            path: '/openai/v1/chat/completions',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${GROQ_API_KEY}`
            }
        }, (res) => {
            let body = '';
            res.on('data', chunk => body += chunk);
            res.on('end', () => {
                try {
                    const json = JSON.parse(body);
                    resolve(json.choices[0]?.message?.content || "Auto-generated changelog failed.");
                } catch (e) {
                    console.error("Groq Parse Error:", body);
                    resolve("Failed to generate changelog via AI.");
                }
            });
        });

        req.on('error', (e) => {
            console.error("Groq Request Error:", e);
            resolve("Failed to reach Groq API.");
        });

        req.write(data);
        req.end();
    });
}

// --- Main ---
(async () => {
    try {
        console.log("🚀 Starting Release Process (Root: " + PROJECT_ROOT + ")...");

        // 1. Read Package.json
        const pkg = require(PACKAGE_JSON_PATH);
        const currentVersion = pkg.version;
        const [major, minor, patch] = currentVersion.split('.').map(Number);

        // 2. Bump Version
        const newVersion = `${major}.${minor}.${patch + 1}`;
        console.log(`🆙 Bumping version: ${currentVersion} -> ${newVersion}`);

        // 3. Get Commits (Run git from ROOT)
        let commits = '';
        try {
            commits = execSync(`git log $(git describe --tags --abbrev=0 2>/dev/null)..HEAD --oneline`, { cwd: PROJECT_ROOT, encoding: 'utf8' }).trim();
        } catch (e) {
            commits = '';
        }

        if (!commits) {
            console.log("⚠️ No tags found, using last 10 commits.");
            commits = execSync('git log -n 10 --oneline', { cwd: PROJECT_ROOT, encoding: 'utf8' }).trim();
        }

        // 4. Generate AI Changelog
        const aiChangelog = await generateChangelog(commits);
        console.log("\n📝 Generated Changelog to Prepend:\n");
        console.log("------------------------------------------------");
        console.log(aiChangelog);
        console.log("------------------------------------------------\n");

        // 5. Update Files (File writes are absolute paths so they work fine)

        // package.json
        pkg.version = newVersion;
        fs.writeFileSync(PACKAGE_JSON_PATH, JSON.stringify(pkg, null, 2) + '\n');

        // version.ts
        const versionTsContent = `// This file is auto-generated by the push script. Do not edit manually.\nexport const APP_VERSION = "${newVersion}";\n`;
        fs.writeFileSync(VERSION_TS_PATH, versionTsContent);

        // CHANGELOG.md (Prepend)
        const date = new Date().toISOString().split('T')[0];
        const newEntry = `\n## v${newVersion} (${date})\n\n${aiChangelog}\n\n`;

        // Correct path handling if one level up or root
        let changelogContent = '';
        if (fs.existsSync(CHANGELOG_PATH)) {
            changelogContent = fs.readFileSync(CHANGELOG_PATH, 'utf8');
        }
        fs.writeFileSync(CHANGELOG_PATH, newEntry + changelogContent);

        // 6. Git Operations (Run from ROOT to include CHANGELOG.md)
        console.log("📦 Committing and Pushing...");
        execSync('git add .', { cwd: PROJECT_ROOT, stdio: 'inherit' });
        execSync(`git commit -m "chore: release v${newVersion} 🚀"`, { cwd: PROJECT_ROOT, stdio: 'inherit' });
        execSync('git push origin main', { cwd: PROJECT_ROOT, stdio: 'inherit' });

        console.log(`\n✅ Successfully released v${newVersion}!`);

        // 7. Deploy Supabase Functions (Run from ROOT)
        console.log("⚡️ Deploying Supabase Edge Functions...");
        try {
            execSync('npx supabase functions deploy --no-verify-jwt', { cwd: PROJECT_ROOT, stdio: 'inherit' });
            console.log("✅ Supabase Functions Deployed!");
        } catch (err) {
            console.error("⚠️ Supabase deployment failed (but git push succeeded). Check logs.");
        }

    } catch (e) {
        console.error("\n❌ Script Failed:", e);
        process.exit(1);
    }
})();
